### ISSUE TITLE
Need a help maybe?

### ISSUE THREAD

**Issue by jayarjo** [ffalt/jamp3#124]
I was looking for a good ID3 read-write module. You seem to have the most feature-full (supports both v1, v2) and the most thoroughly tested one out there. What are it's shortcomings? According to readme it is still a work in progress. Is there a place where you need a hand?

**Comment by ffalt** [comment]
Hi, beside some rarely found features like id3v2 unsynchronisation scheme or extended headers, I'm not aware of mayor shortcomings in write support. Help is most certainly welcome at every place you like to contribute, from code to documentation to just feature requests. Thank you!
I'll try to update the readme in the next days to document writing.

**Comment by ffalt** [comment]
documentation and some more write features like default string encoding are available now in v0.4. please let me know if you encounter any issues.

**Comment by jayarjo** [comment]
@ffalt I've got a question about your library and your availability for hired work in general. I've added you on Twitter, but I see you need to approve me first. Would you?
