### ISSUE TITLE
id3v2 write() function removes .bak files even if keepBackup is false

### ISSUE THREAD

**Issue by jsgrosman** [ffalt/jamp3#186]
i was writing a unit test, and saved the original file as *.bak, in order to restore the file to it's pre-test state at the end.

However, the afterTest() function failed because the .bak file disappeared during the execution of the test.

I had to use a different file extension in order for the test to work.

Why is the code in update-file.ts renaming or removing .bak files if keepBackup is set to false?

**Comment by ffalt** [comment]
Hi, you found a bug. I fixed it and published [v0.4.1](https://github.com/ffalt/jamp3/blob/master/CHANGELOG.md#041-20191206).
Existing .bak files are now ignored as expected. I created [tests](https://github.com/ffalt/jamp3/blob/master/test/common/update-file.test.ts) to make sure.

Thank you!
