### ISSUE TITLE
mp4 support

### ISSUE THREAD

**Issue by universalhandle** [ffalt/jamp3#293]
Hello. `jamp3` does not appear to support the mp4 format, though mp4s do support ID3. Do you have a sense of what adding mp4 support would entail?

**Comment by ffalt** [comment]
Hi, yes, while mp4 brings its own meta tag format, ID3 can be embedded in mp4. A lot of specification would have to be implemented to actually find the frame (and even worse writing it), while in mp3 the id3 justs sits in front or back of the audio. 
Out of scope for this package, sorry.
But, you can use a mp4 parser and feed the id3 tag frame stream to jamp3 and vice versa for writing.

**Comment by universalhandle** [comment]
Thanks.
