### ISSUE TITLE
Fails to install with yarn

### ISSUE THREAD

**Issue by benash** [ffalt/jamp3#30]
Thanks for your work on this. I currently get an error when trying to install via yarn:

```
> yarn add jamp3
yarn add v1.13.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error jamp3@0.1.10: The engine "node" is incompatible with this module. Expected version "~6.16.0". Got "11.10.0"
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

I can workaround the issue with `yarn install jamp3 --ignore-engines`

**Comment by ffalt** [comment]
Yarn choked on the format of the engines requirement in package.json "~6.16.0" and that needed to be updated anyhow. I changed it to ">=8.0.0", updated the npm package, now yarn likes the package without the workaround. Thank you for the report!

**Comment by benash** [comment]
👍
