### ISSUE TITLE
[BUG]: ID3v2 Tags are not showing up

### ISSUE THREAD

**Issue by EhsanFox** [ffalt/jamp3#340]
Hey,
Hope you are doing well,
Before going deep into the project, I have to say, your work is amazing, keep up the good work,

So the issue is, I created some tags and saved them to the target file (which is MP3)
And I wanted to check and see if the tags have been changed, but the title and others are not showing up (in my music player of mine, which is Windows 10 Groove Music)

```typescript
const tags = new ID3V24TagBuilder(ID3V24TagBuilder.encodings.utf8)
        .title(info.title)
        .artist(info.author.name);
        
this.id3v2.writeBuilder(this.storage.getPath(engine, filename), tags, {
          keepBackup: false,
        })
        .then(() => console.log('id3v2.4 written'));
```

(the console writes the `id3v2.4 written`, so no idea to be honest...)

Note: It's not just Groove Music Player, even file explorer can't seem to detect them.

![image1](https://user-images.githubusercontent.com/20506391/220934672-5d441ceb-a5c9-4840-88f1-673856e3a4a3.png)

![image2](https://user-images.githubusercontent.com/20506391/220945208-34c0d656-9f9d-477f-845e-5806cd95d298.png)

**Comment by ffalt** [comment]
Hi! Thanks!

I have two ideas:
a) Win 10 Explorer and/or Groove Music Player may not support UTF8 encoding, 
    please try 
```js	
const builder = new ID3V24TagBuilder(ID3V24TagBuilder.encodings.iso88591);
```
b) Win 10 Explorer and/or Groove Music Player may not support ID3v2.4 encoding, 
    please try saving as v2.3
```js	
 const builder = new ID3V24TagBuilder(ID3V24TagBuilder.encodings.utf8);
	builder
		.album('An album')
		.artist('An artist')
		.title('A title');
	const version = 3;  // version: 2 = v2.2; 3 = v2.3; 4 = v2.4
   id3v2.write(filename, {frames: builder.buildFrames()}, version, 0, { keepBackup: true })
	 .then(() => console.log('id3v2.3 written'));
```
Building v2.4 but writing v2.3 should be fine for most basic tags, but there are incompatible ones. So it is not ideal.

For Windows 10 Explorer b) is most probably the case according to https://answers.microsoft.com/en-us/windows/forum/all/id3-tag-24-support-in-windows-10-explorer-windows/c9c5caf0-93c9-4b34-9152-fff5d870d426

Hope this helps.

**Comment by EhsanFox** [comment]
Hey, Sorry for the late response,

I've just tried both ways you have mentioned above, seems that none of them did the trick for me,

![image](https://user-images.githubusercontent.com/20506391/224508082-2d523a78-ee1d-4926-b79b-ca5e120f3467.png)
![image](https://user-images.githubusercontent.com/20506391/224508095-6264e3d7-8dfc-4185-bce0-efc87ae679e7.png)
