### ISSUE TITLE
Support for buffer and streams

### ISSUE THREAD

**Issue by Capossito** [ffalt/jamp3#40]
do you plan on adding support for buffer and streams?

**Comment by ffalt** [comment]
not in the near future, since I want to finish write support & documentation first. but I'll keep this issue open as a reminder.

**Comment by ffalt** [comment]
Internally I used already streams (wrapped into a helper class), so I added functions for generic Node.js Readable Streams.
```
MP3.readStream(stream: Readable, opts: IMP3.ReadOptions, streamSize?: number): Promise<IMP3.Result>;
ID3V1.readStream(stream: Readable): Promise<IID3V1.Tag | undefined> 
ID3v2.readStream(stream: Readable): Promise<IID3V2.Tag | undefined> 
```
in v0.3.0.
