### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by dogwatch** [ffalt/jamp3#85]
https://github.com/ffalt/jamp3/blob/77d169b82bbb49b19931364fed6e8ef46e0b5095/src/lib/id3v2/id3v2_simplify.ts#L218

AIMP writes COMM without an identifier.

foobar2000 uses TXXX|COMMENT for comment.

**Comment by ffalt** [comment]
ok, frames without a value identifier are now [0.3.3](https://www.npmjs.com/package/jamp3/v/0.3.3) included in the simplified version with just their frame id.
thanks!
