### ISSUE TITLE
MP3.removeTags

### ISSUE THREAD

**Issue by dogwatch** [ffalt/jamp3#89]
One more wish.  ;) Thanks.

`TagTypes MP3.removeTags(fileOrStream, tagTypes)`

**Comment by ffalt** [comment]
hi, I've added `MP3.removeTags(filename:string, opts:{id3v2:boolean, id3v1:boolean, keepBackup?:boolean):Promise<void>`
 in [v0.3.7](https://github.com/ffalt/jamp3/blob/master/CHANGELOG.md#0.3.7)
cleaning a stream requires more change to how the MP3 scanning process is implemented, so it's not there.

**Comment by dogwatch** [comment]
How to find out the result?

sort of:
`const r = await mp3.removeTags(fn, {id3v2: true});
if ( r && r.id3v2 ) {
    // ...
}`

**Comment by dogwatch** [comment]
> 0.3.7 (2019/0**7**/03)

**Comment by ffalt** [comment]
if the Promise is not rejected, the operation was a success.
```
mp3.removeTags(...)
    .then(()=>{console.log('success');}
    .catch(e=>{console.error(e);}
```
or in a async function
```
try {
    await mp3.removeTags(...);
    console.log('success');
  } catch(e) {
    console.error(e);
  }
```
Version date is fixed in changelog.md, thanks.

**Comment by dogwatch** [comment]
```
const r = await mp3.removeTags(fn, {id3v1: true, id3v2: true});
if ( r ) {
  // was deletion

  if ( r.id3v2 ) {
    // id3v2 removed
  }
}

```

**Comment by dogwatch** [comment]
This is not about an error, it was about whether something was removed from the file or not.

**Comment by ffalt** [comment]
ok, if not tags to remove are found, it will return nothing, a report obj {id3v1: boolean, id3v2: boolean} otherwise. [0.3.9](https://github.com/ffalt/jamp3/blob/master/CHANGELOG.md#0.3.9)

**Comment by dogwatch** [comment]
Thank you. ;)
